### ISSUE TITLE
How does CppADCG export compile definitions?

### ISSUE THREAD

**Issue by markusgft** [joaoleal/CppADCodeGen#30]
Dear @joaoleal,

I have been trying to use llvm-based JIT (without creating dynamic libraries) in an external project.

I noticed that I cannot find any place where a previously installed instance of CppADCG exports the compile definitions that were allocated in the original CMakeLists.txt in the CppADCG root folder (e.g. found version of llvm, etc.)
For instance, when including LLVM and CppADCG, an external project needs to access the LLVM version compile definitions in this [header](https://github.com/joaoleal/CppADCodeGen/blob/master/include/cppad/cg/model/llvm/llvm.hpp).

How does CppADCG currently export its compile definitions, and what is the appropriate way for other projects to retrieve them?

_____________
_Since CppADCG is header-only, one possible workflow would be to declare cppadcg as an interface library, e.g. include something like_
```
add_library(cppadcg INTERFACE)
target_compile_definitions(cppadcg INTERFACE ${<some_compile_definitions>})
```
_in which case an external project will receive all CppADCG internal compile-definitions automatically when linking against the interface library_
`target_link_libraries(<some_external_project> INTERFACE cppadcg)`_

**Comment by joaoleal** [comment]
Hello Markus,

Since CppADCodeGen is a header-only library, the LLVM/Clang definitions must be defined in your project.
At the moment there is no code to help you export the compile definitions since this is project-specific.
Only should only need these if you compile a library that uses CppADCodeGen which is called by another library or executable which also uses CppADCodeGen (the same is applicable to CppAD).

Regarding LLVM/Clang, you could copy the files [FindClang.cmake](https://github.com/joaoleal/CppADCodeGen/blob/master/cmake/FindClang.cmake) and [FindLLVM.cmake](https://github.com/joaoleal/CppADCodeGen/blob/master/cmake/FindLLVM.cmake) from CppADCodegen into a `cmake/` folder in your project and  then use then as:
```CMake
SET(CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/cmake)
FIND_PACKAGE(LLVM ${LLVM_VERSION})
FIND_PACKAGE(Clang ${LLVM_VERSION})
IF(LLVM_FOUND)
    ADD_DEFINITIONS(-DLLVM_VERSION_MAJOR=${LLVM_VERSION_MAJOR}
                    -DLLVM_VERSION_MINOR=${LLVM_VERSION_MINOR})
ENDIF()
```

Using `target_compile_definitions` appears to be a good idea so that CppADCodeGen can be used by a second library or executable but the `${<some_compile_definitions>}` will be the ones used in your library.

**Comment by markusgft** [comment]
Dear @joaoleal , thanks for your quick reply, your suggestion makes a lot of sense to me.

One potential drawback may be that users would have to maintain their own "clones" of the cmake find scripts for llvm and clang, e.g. when new versions are released. 
Also, I am not sure if it is generally a scalable solution to copy cmake find-scripts, e.g. let us consider case where you want to create chain of header-only libraries that include each other subsequently. To minimize the number of copied cmake find sripts, already the very top dependency should create an interface library target and export all its compile-definitions throughly. 
So, given that, I still believe that users would benefit from getting exported compile definitions directly from the CppADCG package config file (good notes on this topic which helped me understand my issue are also [here ](http://mariobadr.com/creating-a-header-only-library-with-cmake.html)and [here ](https://pabloariasal.github.io/2018/02/19/its-time-to-do-cmake-right/).

Or maybe asked slightly differently, do you see any immediate drawbacks in declaring CppADCG an interface target and adding the compile definitions via target_compile_definitions() ?

----------

PS: An advantage of the solution you propose above is that the order of installing CppADCG and LLVM would not matter - you can also install LLVM after CppADCG and still get the compile definitions set correctly....

In any case, thanks again!

**Comment by joaoleal** [comment]
Since CppADCodeGen supports multiple versions of LLVM/Clang, installing a predefined export CMake file with compile definitions means that CppADCodeGen would be limiting the users of the library. They may not even have the version of LLVM that I selected in CppADCodeGen.

What could be done is to provide a FindCppADCodeGen.cmake that would accept the Clang/LLVM version.
It would still be up to the user to make sure the same version of LLVM is used throughout the chain of libraries.
Would you be interested in this?

I do not see any drawback in configuring CppADCG as an interface library.
