### ISSUE TITLE
Need to gaurd against including cppad.hpp before cppadcg.hpp

### ISSUE THREAD

**Issue by bradbell** [joaoleal/CppADCodeGen#45]
Using gcc 9.2.1 the program below generates a compile error. It can be fixed by switching the order of the include commands:

    # include <cppad/cppad.hpp>
    # include <cppad/cg/cppadcg.hpp>
    int main(void)
    {
        typedef CppAD::cg::CG<double>        cg_double;
        typedef CppAD::AD<cg_double>         cppadcg_double;
        cppadcg_double r;
        r = 0.0;
        if( CppAD::IdenticalZero(r) )
            return 0;
        return 1;
    }

**Comment by joaoleal** [comment]
CppADCodeGen must be included before CppAD.
Actually, there is no need to include CppAD because CppADCodeGen already does this in the expected order.
The issue is related to some CppADCodeGen files having to be included after `cppad/base_require.hpp` but before the rest of CppAD headers.

`IdenticalEqualCon<CG<Base>>` and `IdenticalEqualCon<CG<Base>>` must be defined in the cppad namespace before CppAD is included.

**Comment by bradbell** [comment]
I just thought that since it took me a while to realize what I had done wrong, something like this at the top of cppadcg.hpp would help other users:

    // --------------------------------------------------------------------------
    // System routines that can be used by rest of CppAD with out including
    # ifdef CPPAD_CPPAD_HPP
    static_assert(false, 
    "\ncppad/cppad.hpp was included before cppad/cg/cppadcg.hpp\n"
    "cppadcg.hpp includes cppad.hpp with the proper environment for CppADCodeGen"
    );
    # endif

I have not made CPPAD_CPPAD_HPP part of the API, but I could.

**Comment by joaoleal** [comment]
That sounds good. I'll add the check to CppADCodeGen.
