### ISSUE TITLE
How does sparsity detection work?

### ISSUE THREAD

**Issue by aespielberg** [joaoleal/CppADCodeGen#8]
I have a few quick questions about the sparsity detection that I couldn't figure out from the docs:

1. It seems from the code that the system evaluates the function once on dummy variables, see which elements of the result are non-empty, and from that, determines the sparsity.  Is this correct?  If so, how are conditionals in an expression handled?  Are they safe here?

2. How does, say, SparseJacobian() work?  Is using :
        ```
        cgen.setCreateSparseJacobian(true);
        cgen.setCustomSparseJacobianElements(rows, cols);
```

The same as using:

`fun.SparseJacobian(x0)`
with
`cgen.setCreateForwardZero(true);`

3. I haven't tried this yet, nor do I know if it's supported, but how would this play with Eigen's SparseMatrix (on input elements)?

**Comment by bradbell** [comment]
There are some problems with Eigen's sparse matrices and auto-differentiation. I know how to fix it, but I would like someone else to do it. I am willing to help. See
http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1480

**Comment by aespielberg** [comment]
Thank you for the info.  Let me think about that and see how much work it is to make that change (or really, mostly, to understand what needs to happen), though no guarantees whatsoever that I can do that.

On that note though, if I'm understanding correctly, Eigen detects when an entry drops to 0 and removes it from the indexing in its sparse representation.  This is certainly a problem for CppAD, but what about with codegen?  Maybe there's a workaround at least here.

It seems the values don't actually matter for code-generation, rather, how the symbols move around and interact is what matters.  However, if I'm not mistaken, the as ADCGs are passed around, they still store a value, and their product or whatever can go to 0, and the same problem will emerge.  But what if you were to initialize it to an absurd value, say, Inf?  I don't know if Eigen shortcuts computation for Infs or nans, so maybe this is also a bad idea.  But as long as it were a special type that could never go back to identically 0, that might be a safe thing to do.

Let me know if I misunderstood anything about how this all works in the background.  Sorry, I'm relatively new to this all.

**Comment by bradbell** [comment]
I think you could create a CodeGen example that is like my Eigen bug report and that does not work properly.

**Comment by joaoleal** [comment]
CodeGen uses the CG type so that it its possible to easily use the operation graph outside of CppAD (and in some cases manipulate it).
The numerical values do not really matter.

CppADCodeGen considers an immutable sparsity pattern.
When handling conditions, since it not possible to know beforehand, CppADCodeGen uses a sparsity pattern that considers all options/branches. Therefore, when a branch of a conditional statement is used, the sparsity that is solely related to other branch will just lead to elements with zeros in the sparse representation.

The method:
```C++
cgen.setCustomSparseJacobianElements(rows, cols);
```
should only be used if want to define different sparsity pattern than the one computed by CppAD. 
This can be useful when you do not need all the derivatives to be computed or require a different order.
If you do not need this then just let it compute the sparsity for you.
You can get the sparsity by calling one of the following methods:
```C++
auto model = dynamicLib->model("model");

std::vector<std::set<size_t> > s1 = model->JacobianSparsitySet();

std::vector<bool> s2 = model->JacobianSparsityBool();

std::vector<size_t> equations, variables;
model->JacobianSparsity(equations, variables);
```
There are similar methods for the Hessian.
See [generic_model.hpp](https://github.com/joaoleal/CppADCodeGen/blob/master/include/cppad/cg/model/generic_model.hpp) documentation for more info.

### CppADCodeGen+Eigen
- Using the ouptut of CppADCodeGen with Eigen:
 If you would like to use the a Jacobian or Hessian computed by CppADCodeGen, then you can either copy the values to an `Eigen::SparseMatrix<>` or use an `Eigen::Map< SparseMatrix<> >` which avoids copies.

- Using an `Eigen::SparseMatrix` as input to CppADCodeGen:
 CppADCodeGen does not really care about the fact that the values are contained in a `SparseMatrix<AD<CG<>>>`, just the order they are provided. 
If you always provide the same number of elements in the same order then it should work fine.

I'm not really familiar with the AutoDiffScalar to provide help.
There a helper header in CppADCodeGen for Eigen [here](https://github.com/joaoleal/CppADCodeGen/blob/master/include/cppad/cg/support/cppadcg_eigen.hpp) and a test related to that [here](https://github.com/joaoleal/CppADCodeGen/blob/master/test/cppad/cg/support/cppadcg_eigen.cpp).

**Comment by fdevinc** [comment]
>    If you would like to use the a Jacobian or Hessian computed by CppADCodeGen, then you can either copy the values to an Eigen::SparseMatrix<> or use an Eigen::Map< SparseMatrix<> > which avoids copies.

Hi! I have a question about this point: have you ever tried `Eigen::Map<Eigen::SparseMatrix<...>>` to directly use the outputs of CppADCodeGen? I did, and it looks like this approach is troublesome. For instance, CppADCodeGen stores the data for the matrix
```cpp
  1.51612  0.864777 -0.406674   1.34488
  3.97493         0         0         0
```
as the array
```cpp
[1.34488, -0.406674, 0.864777, 1.51612, 3.97493]
```
This is a row major representation where the rows are stored from right to left. This means that they are sorted by **decreasing** inner indices, which is in contrast to [Eigen's implementation](https://eigen.tuxfamily.org/dox/group__TutorialSparse.html):
> Currently the elements of a given inner vector are guaranteed to be always sorted by increasing inner indices.

**_Is there an easy way to store the rows by increasing column indices with CppADCodeGen?_** That would solve all problems and would allow using `Eigen::Map` on CppADCodeGen outputs.

For completeness, the above example would translate to the following:
```cpp
Data:             [1.51612, 0.864777, -0.406674, 1.34488, 3.97493]
Inner indices:    [0, 1, 2, 3, 0]
Outer starts:     [0, 4, 5]
```
